sudo: required

dist: trusty

language: node_js

node_js:
  - '10'

cache: yarn

matrix:
  allow_failures:

jobs:
  include:
    - stage: "test"
      name: "Test"
      script: yarn build
      name: "Build"
    - stage: deploy
      name: "Deploy to live"
      script: yarn deploy

stages:
  - name: test
    if: branch != master
  - name: deploy
    if: branch = master

notifications:
  email: false
