sudo: required

dist: trusty

language: node_js

node_js:
  - "10"

install:
  - npm install
  - npm install -g surge

matrix:
  allow_failures:

script:
  - npm run build

notifications:
  email: false
